CREATE DATABASE IF NOT EXISTS e_perpustakaan;
USE e_perpustakaan;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','GURU','SISWA') NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(150) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  cover VARCHAR(500),
  category VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS reading_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  duration INT NOT NULL DEFAULT 0,
  progress INT NOT NULL DEFAULT 0,
  last_page INT NOT NULL DEFAULT 1,
  started_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  CONSTRAINT fk_read_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_read_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);
